# Generated by Django 5.2.3 on 2025-10-28 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta de Test',
                'verbose_name_plural': 'Preguntas de Test',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SesionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_lectura', models.DurationField(blank=True, null=True)),
                ('respuestas_correctas', models.PositiveSmallIntegerField(default=0)),
                ('total_preguntas', models.PositiveSmallIntegerField(default=20)),
                ('velocidad_lectura', models.PositiveIntegerField(default=0)),
                ('velocidad_memorizacion', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sesión de Test',
                'verbose_name_plural': 'Sesiones de Test',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TestLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('texto_titulo', models.CharField(max_length=200)),
                ('texto_contenido', models.TextField()),
                ('texto_autor', models.CharField(blank=True, max_length=100)),
                ('numero_palabras', models.PositiveIntegerField(default=0)),
                ('dificultad', models.CharField(choices=[('inicial', 'Test Inicial'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='inicial', max_length=15)),
                ('numero_test', models.PositiveSmallIntegerField(default=1)),
                ('requiere_password', models.BooleanField(default=False)),
                ('password_acceso', models.CharField(blank=True, max_length=20)),
                ('requiere_pro', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('test_previo_requerido', models.CharField(blank=True, max_length=50)),
                ('bloque_requerido', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test de Lectura',
                'verbose_name_plural': 'Tests de Lectura',
                'ordering': ['numero_test', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='test_lectura.preguntatest')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_lectura.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_lectura.preguntatest')),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuario',
            },
        ),
    ]
