# Generated by Django 5.2.3 on 2025-10-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_lectura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiontest',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_test', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestausuario',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='test_lectura.sesiontest'),
        ),
        migrations.AddField(
            model_name='sesiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='test_lectura.testlectura'),
        ),
        migrations.AddField(
            model_name='preguntatest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='test_lectura.testlectura'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestausuario',
            unique_together={('sesion', 'pregunta')},
        ),
    ]
