# Generated by Django 5.2.3 on 2025-10-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloquePrevio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque_actual', models.PositiveSmallIntegerField(unique=True)),
                ('bloques_requeridos', models.CharField(max_length=50)),
                ('test_requerido', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Bloque Previo',
                'verbose_name_plural': 'Bloques Previos',
                'ordering': ['bloque_actual'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Ejercicio',
                'verbose_name_plural': 'Categorías de Ejercicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('bloque', models.PositiveSmallIntegerField(default=1)),
                ('orden_en_bloque', models.PositiveSmallIntegerField(default=0)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_pro', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='ejercicios.categoriaejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['bloque', 'categoria__orden', 'orden_en_bloque'],
            },
        ),
    ]
