# Generated by Django 5.2.3 on 2025-10-31 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('solicitar_pro', 'Solicitar Pro'), ('volver_gratuito', 'Volver a Gratuito')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesada', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas para gestores')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Plan',
                'verbose_name_plural': 'Solicitudes de Cambio de Plan',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', 'fecha_solicitud'], name='usuarios_so_estado_f42370_idx'), models.Index(fields=['tipo_solicitud', 'estado'], name='usuarios_so_tipo_so_434aa9_idx')],
                'unique_together': {('usuario', 'estado')},
            },
        ),
    ]
