# Generated by Django 5.2.3 on 2025-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudcambioplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudcambioplan',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='solicitudcambioplan',
            index=models.Index(fields=['usuario', 'estado'], name='usuarios_so_usuario_dbb68c_idx'),
        ),
    ]
